#!/usr/bin/env bash
# warn-on-lockfile-edit.sh
# PreToolUse hook on Edit|Write|MultiEdit
# Non-blocking: warns Claude (and the user) when it tries to hand-edit a lock file.
# Lock files should be regenerated by the package manager, not patched by hand.

set -euo pipefail

if ! command -v jq >/dev/null 2>&1; then
  echo "warn-on-lockfile-edit: jq not installed — skipping (install: brew install jq)" >&2
  exit 0
fi

input="$(cat)"
file_path="$(echo "$input" | jq -r '.tool_input.file_path // .tool_input.path // empty')"

if [[ -z "$file_path" ]]; then
  exit 0
fi

basename_path="$(basename "$file_path")"

case "$basename_path" in
  package-lock.json|pnpm-lock.yaml|yarn.lock|bun.lockb|uv.lock|poetry.lock|Pipfile.lock|Cargo.lock|go.sum)
    cat >&2 <<EOF
warn-on-lockfile-edit: $file_path is a dependency lock file.
Lock files are generated by the package manager; hand-edits are almost always wrong
and tend to cause subtle, late-binding breakage.

If you need to update a dependency:
  • npm/pnpm/yarn: run the relevant install/update command
  • uv:           uv lock --upgrade-package <name>  OR  uv add <name>
  • poetry:       poetry update <name>
  • cargo:        cargo update -p <name>
  • go:           go get <module> && go mod tidy

Proceeding anyway, but reconsider before saving.
EOF
    ;;
esac

exit 0
